//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.Products = new HashSet<Product>();
    }

    public int CategoryID { get; set; }
    public string CategoryName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
}

public partial class Order
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
    }

    public int OrderID { get; set; }
    public string CustomerName { get; set; }
    public System.DateTime OrderDate { get; set; }
    public System.DateTime ShipDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
}

public partial class OrderDetail
{
    public int Id { get; set; }
    public Nullable<int> OrderID { get; set; }
    public Nullable<int> ProductID { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<decimal> UnitCost { get; set; }

    public virtual Order Order { get; set; }
}

public partial class Product
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
        this.Reviews = new HashSet<Review>();
        this.ShoppingCarts = new HashSet<ShoppingCart>();
    }

    public int ProductID { get; set; }
    public int CategoryID { get; set; }
    public string ModelNumber { get; set; }
    public string ModelName { get; set; }
    public string ProductImage { get; set; }
    public decimal UnitCost { get; set; }
    public string Description { get; set; }

    public virtual Category Category { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Review> Reviews { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
}

public partial class Review
{
    public int ReviewID { get; set; }
    public int ProductID { get; set; }
    public string CustomerName { get; set; }
    public string CustomerEmail { get; set; }
    public int Rating { get; set; }
    public string Comments { get; set; }

    public virtual Product Product { get; set; }
}

public partial class ShoppingCart
{
    public int RecordID { get; set; }
    public string CartID { get; set; }
    public int Quantity { get; set; }
    public int ProductID { get; set; }
    public System.DateTime DateCreated { get; set; }

    public virtual Product Product { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class VewOrderDetail
{
    public int ProductID { get; set; }
    public string ModelNumber { get; set; }
    public string ModelName { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<decimal> UnitCost { get; set; }
    public Nullable<int> OrderID { get; set; }
}

public partial class ViewAlsoPurchased
{
    public Nullable<int> ProductID { get; set; }
    public string ModelName { get; set; }
    public Nullable<int> TotalNumPurchased { get; set; }
    public Nullable<int> OrderID { get; set; }
    public int Products_ProductID { get; set; }
}

public partial class ViewCart
{
    public int ProductID { get; set; }
    public string ModelNumber { get; set; }
    public string ModelName { get; set; }
    public decimal UnitCost { get; set; }
    public int Quantity { get; set; }
    public string CartID { get; set; }
}

public partial class SelectPurchasedWithProducts_Result
{
    public Nullable<int> ProductID { get; set; }
    public string ModelName { get; set; }
    public Nullable<int> TotalNum { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
